

services:
  airbnb-explorer-service:
    build: ./backend
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}"
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "${BACKEND_PORT}"]
    
  airbnb-explorer-app:
    build: ./frontend
    ports:
      - "${FRONTEND_PORT}:${FRONTEND_PORT}"
    command: ["serve", "-s", "dist", "-l", "${FRONTEND_PORT}"]


  nginx:
    image: nginx:alpine
    ports:
      - "${NGINX_PORT}:80"
    environment:
      - BACKEND_PORT=${BACKEND_PORT}
      - FRONTEND_PORT=${FRONTEND_PORT}
    volumes:
      - ./nginx.conf:/etc/nginx/templates/default.conf.template:ro
    depends_on:
      - airbnb-explorer-app
      - airbnb-explorer-service