server {
    listen 80;

    location / {
        proxy_pass http://airbnb-explorer-app:${FRONTEND_PORT};
    }

    location /api/ {
        proxy_pass http://airbnb-explorer-service:${BACKEND_PORT}/;
    }
}